# Use the node:20.12.1-slim image as base
FROM node:20.12.1-slim

# Use the environment variable for the door
ARG PORT=3000

# Exponha a porta configurável

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if exists) to the working directory
COPY package*.json ./

# Install dependencies (in production should use npm ci)
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app runs on
EXPOSE ${PORT}

# Command to run the application
CMD ["npm", "start"]
