include:
  - path: ./compose.base.yml

services:
  #
  # APPLICATIONS
  #
  app:
    # hostname: app
    stdin_open: true
    build:
      context: ./../../../projects/app
      dockerfile: Dockerfile.dev
      args:
        PORT: 8080
    volumes:
      - ./../../../projects/app:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
    ports:
      - "8080:8080"
    env_file:
      - ./../../../projects/app/.env.local
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BACKEND_API_BASE_URL: http://localhost:3000
      NEXT_PUBLIC_NEXT_API_BASE_URL: http://localhost:8080
    hostname: app-host
    networks:
      - repohub_net

  api:
    # hostname: api
    build:
      context: ./../../../projects/api
      dockerfile: Dockerfile.dev
      args:
        PORT: 3000
    ports:
      - "3000:3000"
    env_file:
      - ./../../../projects/api/.env
    environment:
      NODE_ENV: development
      PORT: 3000
      LOGGING_LEVEL: debug
      LOGGING_USE_MORGAN: true
      # MARIADB_CONNECTION_URL: mysql://admin:admin@mariadb:3306/local_mariadb
      # REDIS_CONNECTION_URL: redis://default:admin@redis:6379/1
      # RABBITMQ_CONNECTION_URL: amqp://admin:admin@rabbitmq:5672
    volumes:
      - ./../../../projects/api:/home/node/app
      - /home/node/api/node_modules
      - /home/node/api/logs
    hostname: api-host
    networks:
      - repohub_net
