
services:
  #
  # APPLICATIONS
  #

  app:
    hostname: app
    stdin_open: true
    build:
      context: ./../../../projects/app
      dockerfile: Dockerfile.dev
      args:
        PORT: 8080
    volumes:
      - ./../../../projects/app:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next
    ports:
      - "8080:8080"
    env_file:
      - ./../../../projects/app/.env.local
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_BACKEND_API_BASE_URL: http://localhost:3000
      NEXT_PUBLIC_NEXT_API_BASE_URL: http://app:8080
    networks:
      - repohub_net


  api:
    hostname: api
    build:
      context: ./../../../projects/api
      dockerfile: Dockerfile.dev
      args:
        PORT: 3000
    ports:
      - "3000:3000"
    env_file:
      - ./../../../projects/api/.env
    environment:
      NODE_ENV: development
      PORT: 3000
      LOGGING_LEVEL: debug
      LOGGING_USE_MORGAN: true
      MARIADB_CONNECTION_URL: mysql://admin:admin@mariadb:3306/local_mariadb
      REDIS_CONNECTION_URL: redis://default:admin@redis:6379/1
      RABBITMQ_CONNECTION_URL: amqp://admin:admin@rabbitmq:5672
    volumes:
      - ./../../../projects/api:/home/node/app
      - /home/node/api/node_modules
      - /home/node/api/logs
    networks:
      - repohub_net

  # TODO melhoria; consolidar os agentes que realizam atividades em background apartado do projeto de API para permitir escalabilidade e melhor uso dos recursos
  # worker:
  #   build:
  #     context: ./../../../projects/worker
  #     dockerfile: Dockerfile.dev
  #     args:
  #       PORT: 3001
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./../../../projects/worker:/home/node/app
  #   networks:
  #     - repohub_net

  #
  # INFRASTRUCTURE
  #

  rabbitmq:
    image: bitnami/rabbitmq:latest
    environment:
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_VHOST=/
      - RABBITMQ_PLUGINS=rabbitmq_management
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true
    # volumes:
    #   - /path/to/rabbitmq-persistence:/bitnami/rabbitmq/mnesia
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    networks:
      - repohub_net
    deploy:
      resources:
        limits:
          memory: 500M

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/data
    networks:
      - repohub_net

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_DATABASE=local_mariadb
      - MARIADB_ROOT_USER=admin
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_USER=guest
      - MARIADB_PASSWORD=guest
      # - ALLOW_EMPTY_PASSWORD=yes # TL;DR quick setup to development env
    volumes:
      - ./../../modules/mariadb/my.cnf:/etc/my.cnf
      - ./../../modules/mariadb/scripts:/docker-entrypoint-initdb.d
    #   - /path/to/mariadb-persistence:/bitnami/mariadb
    ports:
      - "3306:3306"
    hostname: mariadb
    networks:
      - repohub_net
    deploy:
      resources:
        limits:
          memory: 500M


networks:
  repohub_net: {}

