# Use the node:20.12.1-slim image as base
FROM node:20.12.1-slim

# Use the environment variable for the door
ARG PORT=3000

# Expose the configurable port
EXPOSE ${PORT}

# Set the working directory inside the container
WORKDIR /home/node/app

# Copying the necessary files
COPY package*.json ./

# Installing dependencies
RUN npm install

# Copying the rest of the application files
COPY . .

# Building the application
# RUN npm run build

# Command to run the application
CMD ["npm", "run", "devv"]